apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapps.python.app.uppound.com
  labels:
    language: python
spec:
  compositeTypeRef:
    apiVersion: app.uppound.com/v1alpha1
    kind: XApp
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-uppound-ctpcompose-app-python
    step: demo-function
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
