apiVersion: app.uppound.com/v1alpha1
kind: XApp
metadata:
  name: example
spec:
  compositionSelector:
    matchLabels:
      language: kcl
  parameters:
    id: uppound-aws
    containers:
      - name: frontend
        image: tr0njavolta/uppound-demo-frontend:latest
      - name: backend
        image: tr0njavolta/uppound-demo-backend:latest
    region: us-west-2
    version: "1.27"
    nodes:
      count: 2
      instanceType: t3.small
    size: large
    engine: postgres
    dbVersion: "13.18"
  writeConnectionSecretToRef:
    name: uppound-aws-kubeconfig
    namespace: default
